name: CI pour Nodejs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installations des dépendances
        run: npm install

      - name: Run Tests
        run: npm test

      # - name: Build Application
      #   run: npm run build

      # - name: Deploy to Production
      #   run: |
      #     if [ ${{ github.event_name }} == 'push' ] && [ ${{ github.ref }} == 'refs/heads/main' ]; then
      #       # Deploying the application to production

      #       # Copy the contents of the 'views' folder to the deployment directory
      #       cp -r views/* deployment_directory/

      #       # You may need additional commands for deploying other files or configuring your server
      #       # For example, if you are using Node.js and Express for your server, you might restart the server here
      #       # Example: pm2 restart my_server

      #       echo "Deployment to production completed."
      #     fi
